// AOTMain.cpp — runtime entry point for AOT-compiled Trypillia
// binaries.  This file is compiled into `trypillia_rt` (the
// AOT-friendly static library) and is linked into both the regular
// `trypillia` CLI and any AOT-produced executable.
//
// Symbols defined here:
//   trypillia_aot_main        — the AOT binary's `main`. Reads the
//                               user-specified entry function symbol
//                               (set via the constructor below) and
//                               invokes it.
//   trypillia_aot_set_entry   — installed by the constructor of a
//                               generated trampoline object file
//                               (linked with `--whole-archive`) to
//                               point `trypillia_aot_main` at the
//                               AOT-compiled entry function.
//
// The mechanism: the AOT linker command-line passes
//   --undefined=trypillia_aot_<entryFuncName>
// which forces the linker to fail if the symbol is not resolved.
// The user-side linker command then provides an additional .o
// (trampoline.o, generated by AOTModule) whose only job is to
// call trypillia_aot_set_entry("trypillia_aot_<entryFuncName>")
// from a global constructor.
//
// This indirection lets us keep the runtime library completely
// user-code-agnostic; it has no compile-time knowledge of which
// function the user's program will call.

#include <cstdint>
#include <cstdio>
#include <cstring>

#include "../core/VM.h"

namespace trypillia::aot
{

// Pointer to the resolved AOT-compiled entry function. The
// function signature mirrors the runtime-JIT's JitFunc:
//   double entry(void *vm, double *args, int argCount, double n)
typedef double (*AotEntryFn)(void *vm, double *args, int argCount, double n);

static AotEntryFn g_entry_fn = nullptr;
static const char *g_entry_symbol = nullptr;

extern "C" void trypillia_aot_set_entry(const char *symbol)
{
    g_entry_symbol = symbol;
    // dlsym is not used here; the AOT linker resolves the symbol
    // and the trampoline (see AOTModule) installs a function
    // pointer via trypillia_aot_set_entry_fn.
    g_entry_fn = nullptr;
}

extern "C" void trypillia_aot_set_entry_fn(void *fn)
{
    g_entry_fn = reinterpret_cast<AotEntryFn>(fn);
}

extern "C" int trypillia_aot_main(int argc, char **argv)
{
    if (!g_entry_fn)
    {
        std::fprintf(stderr,
                     "AOT runtime error: no entry function installed. "
                     "(trypillia_aot_set_entry was never called; "
                     "did the AOT linker forget the trampoline object?)\n");
        return 1;
    }

    VM vm;
    // args layout: slot 0 = callee (unused here, the user called us
    // directly), slot 1..argc = script arguments (strings).
    //
    // We mirror what the bytecode-VM does for `print("...")`: it
    // doesn't pre-populate args[] with command-line args; scripts
    // access them via the standard library (e.g. `args` global).
    // For AOT Phase 1, we do not wire up the script-args path —
    // this is consistent with the build target being "compiled
    // numeric/scripting work", not "full CLI parity".
    (void)argc;
    (void)argv;
    (void)g_entry_symbol;

    // Provide a 256-slot scratch args buffer.  All AOT-compiled
    // functions assume args_ptr points to a buffer of at least
    // JIT_MAX_SLOTS doubles (256).
    double args[256] = {0};
    // slot 1: the implicit "n" parameter (JIT's FR0). For a
    // top-level script this is unused, but the ABI requires the
    // slot to exist.
    g_entry_fn(&vm, args, 0, 0.0);
    return 0;
}

} // namespace trypillia::aot
