// AOTTrampoline.cpp — generates a small ELF .o file whose only
// job is to install the AOT entry function pointer at program
// startup via a global constructor (.init_array).
//
// Output: a relocatable ELF64 object file with:
//   - one UNDEF symbol "trypillia_aot_set_entry_fn" (resolved at
//     link time against libtrypillia_rt)
//   - one UNDEF symbol "<entrySymbol>" (the user's AOT-compiled
//     function)
//   - one GLOBAL symbol "trypillia_aot_install_entry" (called
//     from .init_array[0] -- the runtime can either invoke this
//     directly, or we expose a separate "init" entry. For
//     simplicity we put the constructor logic in this file as
//     inline code, but that requires codegen. Phase-1 compromise:
//     we use a single .o that defines an init function and lists
//     it in .init_array via a relocation-only entry. The actual
//     init function body is generated by emitting a small piece
//     of machine code that does the call. This is non-trivial
//     without extending the Encoder, so for Phase 1 we use a
//     simpler trick:
//
//       Provide a header that defines a function with the body
//       expressed as inline assembly via a separate translation
//       unit compiled at AOT-link time using the system C
//       compiler. The AOTModule writes a tiny C file
//       ("trypillia_aot_entry.c") containing the constructor and
//       the link command invokes `cc` to compile it to a .o.
//
// This file is therefore just a thin shim that builds the C
// source for the trampoline and writes it to disk. The .c is
// later compiled by the system C compiler.

#include <fstream>
#include <string>

namespace trypillia::aot
{

// Writes a tiny C source file that, when compiled and linked
// with the AOT object and libtrypillia_rt, installs the AOT entry
// pointer at program startup.  The C file uses a
// __attribute__((constructor)) function to do the work, so we
// don't need to muck with .init_array.
bool writeEntryTrampolineC(const std::string &cPath, const std::string &entrySymbol, std::string &err)
{
    std::ofstream f(cPath);
    if (!f.is_open())
    {
        err = "could not open " + cPath + " for writing";
        return false;
    }
    f << "// Auto-generated by Trypillia AOT. Do not edit.\n";
    f << "#include <stdint.h>\n";
    f << "extern void trypillia_aot_set_entry_fn(void *fn);\n";
    f << "extern double " << entrySymbol << "(void *vm, double *args, int argc, double n);\n";
    f << "extern int trypillia_aot_main(int argc, char **argv);\n";
    f << "__attribute__((constructor)) static void trypillia_aot_install(void) {\n";
    f << "    trypillia_aot_set_entry_fn((void *)" << entrySymbol << ");\n";
    f << "}\n";
    f << "int main(int argc, char **argv) {\n";
    f << "    return trypillia_aot_main(argc, argv);\n";
    f << "}\n";
    return true;
}

} // namespace trypillia::aot
